name: geminabox
version: '0.1'
summary: Geminabox
description: |
  Geminabox

grade: devel
confinement: devmode

apps:
  geminabox:
    daemon: simple
    command: wrappers/geminabox
parts:
  geminabox:
    after: [wrappers]
    plugin: ruby
    ruby-version: "2.3.1"
    gems: [geminabox]
    stage:
      - bin
      - lib
      - config.ru
    prime:
      - bin
      - lib
      - config.ru
    install: |
      cp config.ru $SNAPCRAFT_PART_INSTALL/config.ru
  wrappers:
    plugin: dump
    source: snap/
